In [1]:
import numpy as np
from numpy import dot
from numpy.linalg import norm
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
r1 = np.array([1,1,1, 0, 0, 0])
r2 = np.array([1,1,1, 0, 0, 1])
r3 = np.array([0,0,0, 1, 1, 0])
r4 = np.array([0,0,0, 1, 0, 0])
r5 = np.array([0,0,1, 1, 0, 0])

In [3]:
# Normalisation
r1 = r1/norm(r1)
r2 = r2/norm(r2)
r3 = r3/norm(r3)
r4 = r4/norm(r4)
r5 = r5/norm(r5)
print(r1)
print(r2)

[0.57735027 0.57735027 0.57735027 0.         0.         0.        ]
[0.5 0.5 0.5 0.  0.  0.5]


In [4]:
# dot product
dot(r1, r2)

0.8660254037844388

In [5]:
# Using the cosine similarity function
# we get the same answer.
cosine_similarity(r1.reshape(1,6), r2.reshape(1, 6))

array([[0.8660254]])

In [6]:
u1 = np.array([1,1,0, 1, -1])
u2 = np.array([-1,0,-1, 1, 1])
# f1 is Adventure feature
# f2 - Action is the same array
f1 = np.array([1,1,0, 0, 0])
f2 = f1
# f3 is Science Fiction feature
f3 = np.array([1,1,0, 0, 1])
f4 = np.array([0,0,0, 1, 1])
f5 = np.array([0,0, 1, 0, 0])
f6 = np.array([0,1,0, 0, 0])
# compute cosine similarities of u1 and u2 with the feature vectors
cosine_similarity(u1.reshape(1,5), f1.reshape(1, 5))

array([[0.70710678]])

In [7]:
cosine_similarity(u2.reshape(1,5), f1.reshape(1, 5))

array([[-0.35355339]])

In [8]:
u1p = [cosine_similarity(u1.reshape(1,5), f.reshape(1, 5))[0] for f in [f1, f2, f3, f4, f5, f6]]
u1p = np.array(u1p)
print(u1p)

[[0.70710678]
 [0.70710678]
 [0.28867513]
 [0.        ]
 [0.        ]
 [0.5       ]]


In [9]:
u2p = [cosine_similarity(u2.reshape(1,5), f.reshape(1, 5))[0] for f in [f1, f2, f3, f4, f5, f6]]
u2p = np.array(u2p)
print(u2p)

[[-0.35355339]
 [-0.35355339]
 [ 0.        ]
 [ 0.70710678]
 [-0.5       ]
 [ 0.        ]]


In [10]:
N = 5 # number of items
freq = np.array([2, 2, 3, 3, 1, 1])
ri = 1+np.log(freq/N)
print(ri)

[ 0.08370927  0.08370927  0.48917438  0.48917438 -0.60943791 -0.60943791]


In [11]:
# Preference evaluation for user 1
v = [dot(ri, r) for r in [r1, r2, r3, r4, r5]]
v = np.array(v)
print(v)
p1 = cosine_similarity(v.reshape(1,5), u1.reshape(1, 5))
print(p1)

[ 0.37908409  0.0235775  -0.08503916  0.48917438  0.69179704]
[[0.10727115]]


In [12]:
# Preference  for user 2
p2 = cosine_similarity(v.reshape(1,5), u2.reshape(1, 5))
print(p2)

[[0.47561555]]
